"""empty message

Revision ID: dabf33934a52
Revises: 
Create Date: 2021-11-28 14:38:01.635282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dabf33934a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('pubdate', sa.String(length=20), nullable=True))
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('book', 'pubate')
    op.drop_column('book', 'page')
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(timezone='utf-8'), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.add_column('wish', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.add_column('book', sa.Column('page', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('pubate', mysql.VARCHAR(length=20), nullable=True))
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('book', 'pubdate')
    op.drop_column('book', 'pages')
    op.drop_column('book', 'status')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
